config/routes.rb
Deadrop::Application.routes.draw do

  get 'faq' => 'application#faq'
  get 'how_it_works' => 'application#how_it_works'

  post 'deadrop/create_drop' => 'deadrop#create_drop'
  get 'deadrop/:key' => 'deadrop#index'
  get 'deadrop' => 'deadrop#index_blank'
  post 'deadrop/:key' => 'deadrop#create_drop_from_form'

  post 'chat_room/get_new_messages' => 'chat_room#get_new_messages'
  post 'chat_room/create_message' => 'chat_room#create_message'
  post 'chat_room/create_drop' => 'chat_room#create_chat_room'
  get 'chat_room/:key' => 'chat_room#index'
  get 'chat_room' => 'chat_room#index_blank'
  post 'chat_room/:key' => 'chat_room#create_chat_room_from_form'

  get ':key', :to => redirect("/deadrop/%{key}")

  root :to => 'application#index'

end

app/models/chat_message.rb
class ChatMessage
  include Mongoid::Document
  index :chat_name
  index :create_time
end

app/models/drop.rb
class Drop
  include Mongoid::Document
  index :drop, unique: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #def create_chat_room
  #  chat_room_name = params[:chat_room_name]
  #  chat_room_name = get_random_name if chat_room_name.empty?
  #
  #  redirect_to controller: "chat_room", id: chat_room_name
  #end

end

app/controllers/chat_room_controller.rb
require 'animals'
class ChatRoomController < ApplicationController
  def index
    @messages = ChatMessage.where(chat_name: params[:key]).order_by(:create_time, :desc)
    @count = @messages.count
    unless (@messages.empty?)
      render 'index'
    else
      render 'create_chat_room'
    end
  end

  def index_blank
    redirect_to "/chat_room/#{(0..5).map { rand(36).to_s(36) }.join}"
  end

  def get_new_messages
    current_count = params[:message_count].to_i
    mongo_count = ChatMessage.where(chat_name: params[:key]).count
    @messages = []
    unless (current_count == mongo_count)
      @messages = ChatMessage.where(chat_name: params[:key]).order_by(:create_time, :desc).limit(mongo_count - current_count)
    end
    render :partial => 'messages'
  end

  def create_chat_room_from_form
    #make username unique to keep from spoofing
    session[:animal] ||= Animals::Names.sample
    message = ChatMessage.new()
    message['chat_name'] = params[:key]
    message['data'] = params[:encrypted_message]
    message['username'] = "#{session[:animal]} #{params[:username].empty? ? '' : "(#{params[:username]})"}"
    message['create_time'] = Time.now
    message.save!

    redirect_to action: 'index'
  end

  def create_message
    session[:animal] ||= Animals::Names.sample
    message = ChatMessage.new()
    message['chat_name'] = params[:key]
    message['data'] = params[:encrypted_message]
    message['username'] = "#{session[:animal]} #{params[:username].empty? ? '' : "(#{params[:username]})"}"
    message['create_time'] = Time.now
    message.save!

    render nothing: true
  end
end

app/controllers/deadrop_controller.rb
require 'json'
class DeadropController < ApplicationController

  def index
    @drop = Drop.where(drop: params[:key]).first

    unless (@drop)
      render "create_drop"
    else
      render 'index'
    end
  end

  def index_blank
    redirect_to "/deadrop/#{(0..5).map { rand(36).to_s(36) }.join}"
  end

  def create_drop_from_form
    drop = Drop.new()
    drop['drop'] = params[:key]
    drop['data'] = params[:encrypted_object]
    drop['create_time'] = Time.now
    drop.save!

    redirect_to action: 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deadrop_helper.rb
module DeadropHelper
end

app/views/application/_create_form.haml
.span10
  %p
    = text_field_tag :drop_name, nil, class: 'input-medium search-query', placeholder: 'Random'
    = button_tag 'Create Drop', id: 'create_drop_button', class: 'btn btn-primary btn-large'
    = button_tag 'Create Chat', id: 'create_chat_room_button', class: 'btn btn-primary btn-large'

app/views/application/faq.haml
.content_pane
  %h1.header Frequently Asked Questions
  .left_column
    %p
      FAQ is in development.  Please use the
      = succeed '.' do
        = link_to 'blog', 'http://deadropus.blogspot.com/'
      for now.

app/views/application/how_it_works.haml
= javascript_include_tag 'homepage'

.content_pane
  %h1.header How it Works
  .left_column
    %p
      Deadrop is dedicated to keeping your communications private and secure. As a first iteration, you will have the
      capability to post large messages completely secure and
      = succeed '.' do
        = link_to 'encrypted', 'http://en.wikipedia.org/wiki/Encryption'
      Only a person who has the unique link (ex: 'http://deadrop.us/my_secret_message') and the encryption key
      (password) will be able to read the message. The message is encrypted and decrypted on the user’s computer so the server never has access the encryption key (password) or the unencrypted message. See our tutorial to get started or just create a new drop below.  Although no method is completely secure, there are inherent risk to Javascript encryption that is addressed in our
      = succeed '.' do
        = link_to 'blog', 'http://deadropus.blogspot.com/'
  = render 'create_form'
  .clearfix

app/views/application/index.haml
= javascript_include_tag 'homepage'

.content_pane
  %h1.header Welcome to Deadrop
  .span6
    %p
      We enable simple and secure communication via the web browser.
      -#In today’s world, it is hard to have a private conversation via anything but face-to-face communication.

      To learn how Deadrop works, check out our
      = succeed ',' do
        = link_to 'How it Works page', controller: 'application', action: 'how_it_works'
      our
      = succeed ',' do
        = link_to 'Frequently asked Questions page', controller: 'application', action: 'faq'
      or our
      = succeed '.' do
        = link_to 'Blog', 'http://deadropus.blogspot.com', target: "_blank"
      %h2 Get Started!
      %ol
        %li Click on 'Create Drop' or 'Create Chat' below
        %li Enter a password to secure your message
        %li Enter a message and submit
        %li Send or tell the URL to someone
  .span3.offset1
    %h2 What's New?
    %p
      Deadrop.us now supports
      = succeed '!' do
        = link_to 'Chat Rooms', chat_room_path
      Click the 'Create Chat' button to get started.
  = render 'create_form'
  .clearfix

-#<form class="well form-search">
-#  <input type="text" class="input-medium search-query">
-#  <button type="submit" class="btn">Search</button>
-#</form>

app/views/chat_room/_messages.haml
- @messages.each do |message|
  .control-group
    %label.control-label.message_label{for: 'encrypted_text'}
      = message.username
      .time= message.create_time.strftime("%m-%d-%Y %H:%M:%S")
    .controls
      %p#encrytped_test.input-xxlarge.message= message.data
      -#%p.help_block Help text here

app/views/chat_room/create_chat_room.haml
= javascript_include_tag 'create_chat', 'sjcl'

.content_pane
  .form-horizontal
    %fieldset.fieldset_with_header
      %legend Create a Chat Room
      .control-group
        %label.control-label{for: 'password'} Password
        .controls
          = password_field_tag :password, nil, class: 'input-xxlarge'
          %p.help_block Your encryption key
      .control-group
        %label.control-label{for: 'password'} Username
        .controls
          = text_field_tag :username_display, nil, class: 'input-xxlarge', limit: 30
          %p.help_block Username to display on message
      .control-group
        %label.control-label{for: 'text'} Message
        .controls
          = text_area_tag :text, nil, class: 'input-xxlarge drop_message', maxlength: 10000
          -#%p.help_block Help text here
      .form-actions
        = button_tag 'Create Chat Room', id: 'create_chat', class: 'btn btn-primary'

  = form_tag nil, {id: 'create_form'} do
    = hidden_field_tag :encrypted_message
    = hidden_field_tag :username

app/views/chat_room/index.haml
= javascript_include_tag 'chat_room', 'sjcl'

.content_pane
  .form-horizontal
    %fieldset.fieldset_with_header
      %legend Chat Room
      .control-group
        %label.control-label{for: 'password'} Password
        .controls
          = password_field_tag :password, nil, class: 'input-xxlarge', tabindex: 1
          %p.help_block Your encryption key
      .control-group
        %label.control-label{for: 'password'} Username
        .controls
          = text_field_tag :username_display, nil, class: 'input-xxlarge', tabindex: 2, limit: 30
          %p.help_block Username to display on message
      .control-group
        %label.control-label{for: 'text'} Message
        .controls
          = text_area_tag :text, nil, class: 'input-xxlarge chat_entry', tabindex: 3, maxlength: 10000
          -#%p.help_block Help text here
      .form-actions
        = button_tag 'Create Message', id: 'create_message', class: 'btn btn-primary'
        -#= form_tag nil, {id: 'create_message_form'} do
        -#= hidden_field_tag :encrypted_message
        -#= hidden_field_tag :username
      #messages= render :partial => 'messages'
      = hidden_field_tag :chat_room_name, params[:key]

app/views/deadrop/create_drop.haml
-#= javascript_include_tag 'deadrop', 'sjcl'

.content_pane
  .form-horizontal
    %fieldset.fieldset_with_header
      %legend Create a Drop
      .control-group
        %label.control-label{for: 'password'} Password
        .controls
          = password_field_tag :password, nil, class: 'input-xxlarge'
          %p.help_block Your encryption key
      .control-group
        %label.control-label{for: 'text'} Message
        .controls
          = text_area_tag :text, nil, class: 'input-xxlarge drop_message'
          -#%p.help_block Help text here
      .form-actions
        = button_tag 'Create Drop', id: 'create_button', class: 'btn btn-primary'

  = form_tag nil, {id: 'create_form'} do
    = hidden_field_tag :encrypted_object
-#
-#
-#
-#<form class="form-horizontal">
-#  <fieldset>
-#    <legend>Legend text</legend>
-#    <div class="control-group">
-#      <label class="control-label" for="input01">Text input</label>
-#      <div class="controls">
-#        <input type="text" class="input-xlarge" id="input01">
-#        <p class="help-block">Supporting help text</p>
-#      </div>
-#    </div>
-#  </fieldset>
-#</form>

app/views/deadrop/index.haml
= javascript_include_tag 'deadrop', 'sjcl'

.content_pane
  .form-horizontal
    %fieldset.fieldset_with_header
      %legend Drop
      .control-group
        %label.control-label{for: 'password'} Password
        .controls
          = password_field_tag :password, nil, class: 'input-xxlarge'
          %p.help_block Your encryption key
      .control-group
        %label.control-label{for: 'encrypted_text'} Message
        .controls
          = text_area_tag :encrypted_text, @drop.data, class: 'input-xxlarge drop_message', readonly: true
          -#%p.help_block Help text hereta

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deadrop</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30946726-1']);
      _gaq.push(['_setDomainName', 'deadrop.us']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

      (function () {
          var ga = document.createElement('script');
          ga.type = 'text/javascript';
          ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(ga, s);
      })();

  </script>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">
        Deadrop.us
      </a>
      <ul class="nav">
        <li><!--class="active">-->
          <a href="/">Home</a>
        </li>
        <li>
          <%= link_to 'How it Works', controller: 'application', action: 'how_it_works' %>
        </li>
        <li>
          <%= link_to 'Deadrop', deadrop_path %>
        </li>
        <li>
          <%= link_to 'Chat Room', chat_room_path %>
        </li>
        <li>
          <a href="http://deadropus.blogspot.com" target="_blank">Blog</a>
        </li>
        <li>
          <%= link_to 'FAQ', controller: 'application', action: 'faq' %>
        </li>
      </ul>
    </div>
  </div>

</div>

<div class="container">
  <%= yield %>
</div>


</body>
</html>